title: SpeculateQM
description: SpeculateQM is a python project aimed at aleviating the amount of time required to get started in computation chemistry, specifically for undergrads, grads, and/or young researchers.
show_downloads: true
theme: jekyll-theme-hacker
